# Generated by Django 5.1.6 on 2025-03-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatneft',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tatneft',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='war',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='war',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
