# Generated by Django 5.1.6 on 2025-03-08 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tatneft_description_alter_tatneft_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatneft',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
        migrations.AddField(
            model_name='war',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
    ]
