# Generated by Django 5.1.6 on 2025-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tatneft_embedding_war_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='war',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
